workflows:
  android-debug:
    name: NexSketch Debug APK

    max_build_duration: 60

    environment:
      java: 17

      vars:
        GRADLE_OPTS: "-Xmx4096m"

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Grant execute permission
        script: chmod +x gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
