workflows:
  android-debug:
    name: NexSketch Debug APK

    environment:
      java: 17

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
